apiVersion: v1
kind: ConfigMap
metadata: 
  name: mongodb-config
immutable: false  #sothat nobody can update this ,now false so editing possible
data:
  username: admin
  mongodb.conf: |   #configuration for the d ,# | to preserve new lines in yaml
    storage:
      dbPath: /data/configdb
    replication:
        replSetName: "rs0"
